"""The provider-neutral knowledge substrate port."""

from __future__ import annotations

from typing import Protocol

from .types import Document, SearchHit, SearchRequest, Source, SourceRegistration, SubstrateInfo, UpsertResult


class KnowledgeSubstrate(Protocol):
    """A search/ingestion service beneath Mari's management layer.

    Implementations may be remote services such as Onyx or Glean, or a host's
    own index.  Mari remains responsible for facts, decisions, approval,
    lifecycle, lineage, trajectories, prompts, model choice, and generation.
    """

    def info(self) -> SubstrateInfo: ...
    def search(self, request: SearchRequest) -> list[SearchHit]: ...
    def upsert_document(self, document: Document) -> UpsertResult: ...
    def delete_document(self, document_id: str) -> None: ...
    def list_sources(self) -> list[Source]: ...
    def create_source(self, registration: SourceRegistration) -> Source: ...
    def run_source(self, source_id: str, *, full: bool = False) -> str: ...
    def delete_source(self, source_id: str) -> None: ...
