"""Backend-agnostic primitives for versioned knowledge systems."""

from .contracts import Authorizer, Clock, KnowledgeIndex, RevisionResolver, Serializer
from .errors import (
    AuthenticationFailure,
    ComponentError,
    IncompleteSnapshot,
    MalformedModelOutput,
    PermanentFailure,
    TransientFailure,
)
from .references import (
    JsonPointer,
    LocatedEvidence,
    MediaTimeRange,
    ObjectRef,
    PageRegion,
    RecordField,
    RevisionRef,
    ScopeRef,
    TableCell,
    TextSpan,
)
from .types import (
    AnswerCandidate,
    ChangeHint,
    DecisionCandidate,
    DocumentACL,
    Evidence,
    FactCandidate,
    GlossaryCandidate,
    KnowledgeDocument,
    KnowledgeSection,
    PollPage,
    PollRequest,
    Principal,
    SyncMode,
    Tombstone,
    canonical_document_id,
    content_revision,
    parse_document_id,
)

__all__ = [
    "AnswerCandidate",
    "Authorizer",
    "AuthenticationFailure",
    "ChangeHint",
    "Clock",
    "ComponentError",
    "DecisionCandidate",
    "DocumentACL",
    "Evidence",
    "FactCandidate",
    "GlossaryCandidate",
    "IncompleteSnapshot",
    "KnowledgeDocument",
    "KnowledgeIndex",
    "LocatedEvidence",
    "KnowledgeSection",
    "JsonPointer",
    "MalformedModelOutput",
    "MediaTimeRange",
    "ObjectRef",
    "PageRegion",
    "PermanentFailure",
    "PollPage",
    "PollRequest",
    "Principal",
    "RecordField",
    "RevisionRef",
    "RevisionResolver",
    "ScopeRef",
    "SyncMode",
    "Serializer",
    "TableCell",
    "TextSpan",
    "Tombstone",
    "TransientFailure",
    "canonical_document_id",
    "content_revision",
    "parse_document_id",
]
