"""Composable algorithms over caller-owned graph values and callbacks."""

from .adjacency import build_adjacency
from .centrality import (
    betweenness_centrality,
    closeness_centrality,
    degree_centrality,
    hits,
)
from .communities import (
    CommunityPartition,
    CommunityReport,
    build_community_reports,
    leiden_communities,
    map_reduce_reports,
)
from .construction import (
    BlockedPair,
    ClusterDiagnostic,
    ClusterResult,
    EvidenceBoundCandidate,
    EvidenceResolution,
    MatchLink,
    bind_relation_evidence,
    candidate_pairs,
    cluster_matches,
    explain_candidate_pairs,
    inspect_clusters,
    resolve_relation_evidence,
)
from .diagnostics import (
    GraphDiff,
    GraphQualityReport,
    RecordChange,
    RecordDiff,
    diff_records,
    graph_diff,
    inspect_graph_quality,
)
from .interop import (
    EncodedGraph,
    GraphProjection,
    InterchangeReport,
    ProjectionEdge,
    from_networkx,
    to_graphml,
    to_json_ld,
    to_networkx,
    to_pyg_data,
    to_rdflib,
)
from .provenance import (
    LineageEdge,
    LineageEdgeTrace,
    LineageTrace,
    LineageVisit,
    propagated_taints,
    trace_lineage,
    trace_lineage_edges,
)
from .resolution import (
    FieldAgreement,
    ResolutionDecision,
    ResolutionResult,
    fellegi_sunter_score,
    resolve_entity,
)
from .similarity import LinkScore, score_link_candidates, simrank_scores
from .subgraphs import SubgraphSelection, bounded_seed_expansion, prize_guided_subgraph
from .temporal import TemporalFact, close_transaction, query_temporal_facts
from .temporal_tools import (
    TemporalJoinPair,
    TimeInterval,
    close_interval,
    interval_contains,
    interval_intersection,
    intervals_overlap,
    temporal_join,
)
from .traversal import (
    CycleResult,
    PathResult,
    PredecessorDAG,
    PredecessorEntry,
    TraversalResult,
    TraversalVisit,
    breadth_first,
    connected_components,
    directed_cycles,
    k_hop_nodes,
    predecessor_dag,
    shortest_path,
)

__all__ = [
    "BlockedPair",
    "ClusterDiagnostic",
    "CommunityPartition",
    "CommunityReport",
    "ClusterResult",
    "CycleResult",
    "EncodedGraph",
    "EvidenceBoundCandidate",
    "EvidenceResolution",
    "FieldAgreement",
    "GraphDiff",
    "GraphProjection",
    "GraphQualityReport",
    "InterchangeReport",
    "LineageTrace",
    "LineageEdge",
    "LineageEdgeTrace",
    "LineageVisit",
    "LinkScore",
    "MatchLink",
    "PathResult",
    "PredecessorDAG",
    "PredecessorEntry",
    "ProjectionEdge",
    "ResolutionDecision",
    "ResolutionResult",
    "RecordChange",
    "RecordDiff",
    "TemporalFact",
    "TemporalJoinPair",
    "TimeInterval",
    "TraversalResult",
    "TraversalVisit",
    "SubgraphSelection",
    "bounded_seed_expansion",
    "betweenness_centrality",
    "bind_relation_evidence",
    "breadth_first",
    "build_adjacency",
    "build_community_reports",
    "close_transaction",
    "close_interval",
    "closeness_centrality",
    "connected_components",
    "candidate_pairs",
    "cluster_matches",
    "degree_centrality",
    "diff_records",
    "directed_cycles",
    "fellegi_sunter_score",
    "explain_candidate_pairs",
    "graph_diff",
    "from_networkx",
    "hits",
    "inspect_graph_quality",
    "inspect_clusters",
    "interval_contains",
    "interval_intersection",
    "intervals_overlap",
    "k_hop_nodes",
    "query_temporal_facts",
    "leiden_communities",
    "map_reduce_reports",
    "prize_guided_subgraph",
    "predecessor_dag",
    "propagated_taints",
    "resolve_entity",
    "resolve_relation_evidence",
    "score_link_candidates",
    "simrank_scores",
    "shortest_path",
    "temporal_join",
    "to_graphml",
    "to_json_ld",
    "to_networkx",
    "to_pyg_data",
    "to_rdflib",
    "trace_lineage",
    "trace_lineage_edges",
]
